### PR TITLE
some hacks and bug fix

### PR DESCRIPTION
**Pull request by brunobell**
Hi, I got to adore that it's so honorable to have done such a project in this AWEFUL political and internet environment. Good job, dude :+1: 
Basically, I made some fix based on the original code:
1. Removed unwanted spaces and tabs, and fixed some mixture of them two, which may cause ident exception under some certain conditions;
2. Add automatically get current IP address function to make this script more powerful and smart, but if the server is running with multi network devices and want to set the IP address of the secondary card it will need some more improvement;
3. Add .gitignore file to avoid unwanted transfering of files and,
4. Add import from self maintained module to reuse code

(P.S: Since I'm running on fedora23 desktop, I'm not quite sure about the bash files, watch out!)

### CODE REVIEW

**Comment by zyqf** [comment]
Hi, first of all thank you , but there is a problem : api.ipify.org banned by the Chinese network firewall .

I'm trying to modify the code now .

**Comment by zyqf** [comment]
`https  --> http`

The contents obtained are as follows

`<addinfourl at 140198806645504 whose fp = <socket._fileobject object at 0x7f82940f4ad0>>`

**Comment by brunobell** [comment]
Umm it should be that the server is accepting SSLv1 only and refused default SSLv2 when using python2.X. Many other had this problem before so maybe you can try:
`import ssl
ssl.PROTOCOL_SSLv23 = ssl.PROTOCOL_TLSv1`
as mentioned in [this post](https://askubuntu.com/questions/116020/python-https-requests-urllib2-to-some-sites-fail-on-ubuntu-12-04-without-proxy), and also take a look at [this one](https://stackoverflow.com/questions/33972671/downloading-https-pages-with-urllib-error14077438ssl-routinesssl23-get-serve).

**Comment by zyqf** [comment]
Thank you, I modified code that get public network ip automatically,
```
import urllib
import re

def getip():
    url = "http://whois.pconline.com.cn/ipJson.jsp"
    request = urllib.urlopen(url).read()
    myip = re.findall(r"\d{1,3}\.\d{1,3}\.\d{1,3}.\d{1,3}",request)[0]
    if myip:
        return myip
    else:
        raise RuntimeError("Failed to automatically get current IP address!")

IP_ADR = getip()  # no need to manually input current IP now :)
IP_ADR_list = IP_ADR.split('.')
```
Program has successfully built on China and the US server

**Comment by brunobell** [comment]
Good idea to replace the api with a new one. :+1:

**Pull request merged**
